"""Add voice columns for personalization

Revision ID: 002
Revises: 6c3bec1ee993
Create Date: 2025-12-15 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_voice_columns_for_personalization'
down_revision: Union[str, None] = '6c3bec1ee993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые колонки для голосовых сообщений
    op.add_column('users', sa.Column('voice_pay_less_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_5star_3star_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_travel_more_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_passive_income_final_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_free_travel_final_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('voice_quit_job_final_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем добавленные колонки
    op.drop_column('users', 'voice_quit_job_final_id')
    op.drop_column('users', 'voice_free_travel_final_id')
    op.drop_column('users', 'voice_passive_income_final_id')
    op.drop_column('users', 'voice_travel_more_id')
    op.drop_column('users', 'voice_5star_3star_id')
    op.drop_column('users', 'voice_pay_less_id')
    # ### end Alembic commands ###