"""Initial migration

Revision ID: 10526eca99cb
Revises: 
Create Date: 2025-12-14 23:04:15.729411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10526eca99cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_travel_api_logs_created_at', table_name='travel_api_logs')
    op.drop_index('idx_travel_api_logs_tour_id', table_name='travel_api_logs')
    op.drop_index('idx_travel_api_logs_user_created', table_name='travel_api_logs')
    op.drop_index('idx_travel_api_logs_user_id', table_name='travel_api_logs')
    op.drop_table('travel_api_logs')
    op.drop_table('n8n_chat_histories')
    op.drop_index('idx_travel_events_city_date', table_name='travel_events_cache')
    op.drop_table('travel_events_cache')
    op.drop_table('documents')
    op.drop_index('idx_document_rows_dataset_id', table_name='document_rows')
    op.drop_table('document_rows')
    op.drop_index('idx_calendar_events_category_id', table_name='calendar_events')
    op.drop_index('idx_calendar_events_event_date', table_name='calendar_events')
    op.drop_index('idx_calendar_events_user_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('idx_travel_tours_location', table_name='travel_tours')
    op.drop_index('idx_travel_tours_user_id', table_name='travel_tours')
    op.drop_table('travel_tours')
    op.drop_table('document_metadata')
    op.drop_index('idx_travel_hidden_gems_location', table_name='travel_hidden_gems')
    op.drop_index('idx_travel_hidden_gems_submitted_by', table_name='travel_hidden_gems')
    op.drop_table('travel_hidden_gems')
    op.drop_index('idx_task_categories_user_id', table_name='task_categories')
    op.drop_table('task_categories')
    op.drop_index('idx_tasks_category_id', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_order_index', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_tags', table_name='tasks', postgresql_using='gin')
    op.drop_index('idx_tasks_user_id', table_name='tasks')
    op.drop_table('tasks')
    op.alter_column('ai_generations', 'telegram_message_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ai_generations', 'mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ai_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ai_generations_expires_at', table_name='ai_generations')
    op.drop_index('idx_ai_generations_telegram_message_id', table_name='ai_generations')
    op.drop_index('idx_ai_generations_user_id', table_name='ai_generations')
    op.create_index(op.f('ix_ai_generations_created_at'), 'ai_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_generations_expires_at'), 'ai_generations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ai_generations_mode'), 'ai_generations', ['mode'], unique=False)
    op.create_index(op.f('ix_ai_generations_telegram_message_id'), 'ai_generations', ['telegram_message_id'], unique=False)
    op.create_index(op.f('ix_ai_generations_user_id'), 'ai_generations', ['user_id'], unique=False)
    op.drop_constraint('ai_generations_user_id_fkey', 'ai_generations', type_='foreignkey')
    op.create_foreign_key(None, 'ai_generations', 'users', ['user_id'], ['id'])
    op.alter_column('ai_training_sessions', 'user_score',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               comment=None,
               existing_comment='Итоговая оценка от 1 до 10',
               existing_nullable=True)
    op.alter_column('ai_training_sessions', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Массив рекомендаций для пользователя',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_training_sessions', 'strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Сильные стороны пользователя',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_training_sessions', 'weaknesses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Слабые стороны пользователя',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_training_sessions', 'scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Детальные оценки: {product_knowledge, objection_handling, emotional_intelligence, confidence, result}',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_ai_training_sessions_is_active', table_name='ai_training_sessions', postgresql_where='(is_active = true)')
    op.drop_index('idx_ai_training_sessions_opponent_id', table_name='ai_training_sessions')
    op.drop_index('idx_ai_training_sessions_started_at', table_name='ai_training_sessions')
    op.drop_index('idx_ai_training_sessions_user_id', table_name='ai_training_sessions')
    op.create_index(op.f('ix_ai_training_sessions_is_active'), 'ai_training_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_opponent_id'), 'ai_training_sessions', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_started_at'), 'ai_training_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_user_id'), 'ai_training_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_user_score'), 'ai_training_sessions', ['user_score'], unique=False)
    op.drop_table_comment(
        'ai_training_sessions',
        existing_comment='Сессии тренировок с AI-соперниками',
        schema=None
    )
    op.drop_column('ai_training_sessions', 'current_attempt')
    op.drop_column('ai_training_sessions', 'feedback_log')
    op.drop_index('idx_content_ideas_content_type_id', table_name='content_ideas')
    op.drop_index('idx_content_ideas_user_id', table_name='content_ideas')
    op.drop_index('idx_content_ideas_user_saved', table_name='content_ideas', postgresql_where='(is_archived = false)')
    op.create_index(op.f('ix_content_ideas_content_type_id'), 'content_ideas', ['content_type_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_created_at'), 'content_ideas', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_ideas_is_archived'), 'content_ideas', ['is_archived'], unique=False)
    op.create_index(op.f('ix_content_ideas_is_saved'), 'content_ideas', ['is_saved'], unique=False)
    op.create_index(op.f('ix_content_ideas_platform'), 'content_ideas', ['platform'], unique=False)
    op.create_index(op.f('ix_content_ideas_user_id'), 'content_ideas', ['user_id'], unique=False)
    op.drop_constraint('content_ideas_content_type_id_fkey', 'content_ideas', type_='foreignkey')
    op.drop_constraint('content_ideas_user_id_fkey', 'content_ideas', type_='foreignkey')
    op.create_foreign_key(None, 'content_ideas', 'content_types', ['content_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'content_ideas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('content_personal_profiles', 'profile_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('content_personal_profiles_user_id_key', 'content_personal_profiles', type_='unique')
    op.create_index(op.f('ix_content_personal_profiles_user_id'), 'content_personal_profiles', ['user_id'], unique=True)
    op.drop_constraint('content_personal_profiles_user_id_fkey', 'content_personal_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'content_personal_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_content_posts_idea_id', table_name='content_posts')
    op.drop_index('idx_content_posts_user_id', table_name='content_posts')
    op.create_index(op.f('ix_content_posts_created_at'), 'content_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_posts_idea_id'), 'content_posts', ['idea_id'], unique=False)
    op.create_index(op.f('ix_content_posts_platform'), 'content_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_content_posts_status'), 'content_posts', ['status'], unique=False)
    op.create_index(op.f('ix_content_posts_user_id'), 'content_posts', ['user_id'], unique=False)
    op.drop_constraint('content_posts_user_id_fkey', 'content_posts', type_='foreignkey')
    op.drop_constraint('content_posts_idea_id_fkey', 'content_posts', type_='foreignkey')
    op.create_foreign_key(None, 'content_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'content_posts', 'content_ideas', ['idea_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('content_types_code_key', 'content_types', type_='unique')
    op.create_index(op.f('ix_content_types_code'), 'content_types', ['code'], unique=True)
    op.alter_column('knowledge_base', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Категория: цены, документы, партнеры, компенсация, легальность и т.д.',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Ключевые слова для быстрого поиска релевантной информации',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('knowledge_base', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Приоритет информации (чем выше, тем важнее)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_knowledge_base_answer_search', table_name='knowledge_base', postgresql_using='gin')
    op.drop_index('idx_knowledge_base_category', table_name='knowledge_base')
    op.drop_index('idx_knowledge_base_keywords', table_name='knowledge_base', postgresql_using='gin')
    op.drop_index('idx_knowledge_base_priority', table_name='knowledge_base')
    op.drop_index('idx_knowledge_base_question_search', table_name='knowledge_base', postgresql_using='gin')
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_priority'), 'knowledge_base', ['priority'], unique=False)
    op.create_index(op.f('ix_knowledge_base_source_doc'), 'knowledge_base', ['source_doc'], unique=False)
    op.drop_table_comment(
        'knowledge_base',
        existing_comment='База знаний о продукте для AI-тренажера',
        schema=None
    )
    op.alter_column('opponents', 'core_objections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Массив основных возражений соперника',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opponents', 'triggers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Что вызывает агрессию/интерес у соперника',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('opponents', 'response_patterns',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Паттерны реакций соперника',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('opponents', 'base_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Базовый промпт для AI с описанием роли',
               existing_nullable=False)
    op.alter_column('opponents', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"avg_score": 0, "total_attempts": 0, "users_completed": 0}\'::jsonb'))
    op.drop_index('idx_opponents_difficulty', table_name='opponents')
    op.drop_table_comment(
        'opponents',
        existing_comment='Профили AI-соперников для тренажера возражений',
        schema=None
    )
    op.drop_index('idx_profile_voice_chunks_session_id', table_name='profile_voice_chunks')
    op.create_index(op.f('ix_profile_voice_chunks_sequence_number'), 'profile_voice_chunks', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_profile_voice_chunks_session_id'), 'profile_voice_chunks', ['session_id'], unique=False)
    op.drop_index('idx_profile_voice_sessions_user_active', table_name='profile_voice_sessions')
    op.drop_index('idx_profile_voice_sessions_user_id', table_name='profile_voice_sessions')
    op.create_index(op.f('ix_profile_voice_sessions_is_active'), 'profile_voice_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_profile_voice_sessions_user_id'), 'profile_voice_sessions', ['user_id'], unique=False)
    op.drop_constraint('profile_voice_sessions_user_id_fkey', 'profile_voice_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'profile_voice_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_radar_events_lead_id', table_name='radar_events')
    op.drop_index('idx_radar_events_partner_created', table_name='radar_events')
    op.drop_index('idx_radar_events_partner_id', table_name='radar_events')
    op.create_index(op.f('ix_radar_events_action_type'), 'radar_events', ['action_type'], unique=False)
    op.create_index(op.f('ix_radar_events_created_at'), 'radar_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_radar_events_lead_id'), 'radar_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_radar_events_partner_id'), 'radar_events', ['partner_id'], unique=False)
    op.alter_column('training_conversations', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Роль отправителя: user (пользователь), assistant (AI-соперник), system (системные сообщения)',
               existing_nullable=False)
    op.alter_column('training_conversations', 'is_voice',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Было ли сообщение голосовым',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('training_conversations', 'voice_file_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ID голосового файла в Telegram',
               existing_nullable=True)
    op.alter_column('training_conversations', 'emotional_tone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Эмоциональный тон сообщения для анализа',
               existing_nullable=True)
    op.alter_column('training_conversations', 'message_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='Дополнительные метаданные сообщения',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_training_conversations_role', table_name='training_conversations')
    op.drop_index('idx_training_conversations_session_id', table_name='training_conversations')
    op.drop_index('idx_training_conversations_timestamp', table_name='training_conversations')
    op.create_index(op.f('ix_training_conversations_session_id'), 'training_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_conversations_timestamp'), 'training_conversations', ['timestamp'], unique=False)
    op.drop_table_comment(
        'training_conversations',
        existing_comment='История диалогов в AI-тренажере для анализа и контекста',
        schema=None
    )
    op.alter_column('users', 'telegram_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'FREE'::text"))
    op.alter_column('users', 'referral_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_bot_referral_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'consultant_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'voice_passive_income_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'voice_free_travel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'voice_freedom_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'voice_final_cta_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'welcome_video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'current_bot_menu',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'guest'::text"))
    op.drop_index('idx_users_referred_by_user_id', table_name='users')
    op.drop_index('idx_users_telegram_id', table_name='users')
    op.drop_constraint('users_referral_code_key', 'users', type_='unique')
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by_user_id'), 'users', ['referred_by_user_id'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'sigma_ring_link')
    op.drop_column('users', 'consultant_tiktok')
    op.drop_column('users', 'consultant_telegram_channel_photo')
    op.drop_column('users', 'language')
    op.drop_column('users', 'consultant_twitter')
    op.drop_column('users', 'consultant_vkontakte')
    op.drop_column('users', 'travel_architect_last_reset')
    op.drop_column('users', 'travel_architect_quota_month')
    op.drop_column('users', 'consultant_facebook')
    op.drop_column('users', 'consultant_telegram_channel_title')
    op.drop_column('users', 'consultant_telegram_channel')
    op.drop_column('users', 'consultant_telegram_channel_description')
    op.drop_column('users', 'messages_used_today')
    op.drop_column('users', 'travel_architect_used_month')
    op.drop_column('users', 'message_daily_limit')
    # ### end Alembic commands ###

    # Manually added functions
    op.execute("""
    CREATE OR REPLACE FUNCTION public.update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
       NEW.updated_at = now();
       RETURN NEW;
    END;
    $$ language 'plpgsql';
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS TRIGGER AS $$
    BEGIN
        -- Create a personal profile for the new user
        INSERT INTO content_personal_profiles (user_id, profile_data)
        VALUES (NEW.id, '{}'::jsonb);

        -- You can add more actions here, for example:
        -- - Send a welcome message via a custom channel (e.g., using pg_notify)
        -- - Assign a default subscription plan

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('message_daily_limit', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('travel_architect_used_month', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('messages_used_today', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_telegram_channel_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_telegram_channel', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_telegram_channel_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_facebook', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('travel_architect_quota_month', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('travel_architect_last_reset', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_vkontakte', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_twitter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_telegram_channel_photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consultant_tiktok', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sigma_ring_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('users_referral_code_key', 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index('idx_users_referred_by_user_id', 'users', ['referred_by_user_id'], unique=False)
    op.alter_column('users', 'current_bot_menu',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'guest'::text"))
    op.alter_column('users', 'welcome_video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'voice_final_cta_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'voice_freedom_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'voice_free_travel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'voice_passive_income_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'consultant_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_bot_referral_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'FREE'::text"))
    op.alter_column('users', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table_comment(
        'training_conversations',
        'История диалогов в AI-тренажере для анализа и контекста',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_training_conversations_timestamp'), table_name='training_conversations')
    op.drop_index(op.f('ix_training_conversations_session_id'), table_name='training_conversations')
    op.create_index('idx_training_conversations_timestamp', 'training_conversations', ['timestamp'], unique=False)
    op.create_index('idx_training_conversations_session_id', 'training_conversations', ['session_id'], unique=False)
    op.create_index('idx_training_conversations_role', 'training_conversations', ['role'], unique=False)
    op.alter_column('training_conversations', 'message_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Дополнительные метаданные сообщения',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('training_conversations', 'emotional_tone',
               existing_type=sa.VARCHAR(length=50),
               comment='Эмоциональный тон сообщения для анализа',
               existing_nullable=True)
    op.alter_column('training_conversations', 'voice_file_id',
               existing_type=sa.TEXT(),
               comment='ID голосового файла в Telegram',
               existing_nullable=True)
    op.alter_column('training_conversations', 'is_voice',
               existing_type=sa.BOOLEAN(),
               comment='Было ли сообщение голосовым',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('training_conversations', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Роль отправителя: user (пользователь), assistant (AI-соперник), system (системные сообщения)',
               existing_nullable=False)
    op.drop_index(op.f('ix_radar_events_partner_id'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_lead_id'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_created_at'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_action_type'), table_name='radar_events')
    op.create_index('idx_radar_events_partner_id', 'radar_events', ['partner_id'], unique=False)
    op.create_index('idx_radar_events_partner_created', 'radar_events', ['partner_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_radar_events_lead_id', 'radar_events', ['lead_id'], unique=False)
    op.drop_constraint(None, 'profile_voice_sessions', type_='foreignkey')
    op.create_foreign_key('profile_voice_sessions_user_id_fkey', 'profile_voice_sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_profile_voice_sessions_user_id'), table_name='profile_voice_sessions')
    op.drop_index(op.f('ix_profile_voice_sessions_is_active'), table_name='profile_voice_sessions')
    op.create_index('idx_profile_voice_sessions_user_id', 'profile_voice_sessions', ['user_id'], unique=False)
    op.create_index('idx_profile_voice_sessions_user_active', 'profile_voice_sessions', ['user_id', 'is_active', sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_profile_voice_chunks_session_id'), table_name='profile_voice_chunks')
    op.drop_index(op.f('ix_profile_voice_chunks_sequence_number'), table_name='profile_voice_chunks')
    op.create_index('idx_profile_voice_chunks_session_id', 'profile_voice_chunks', ['session_id'], unique=False)
    op.create_table_comment(
        'opponents',
        'Профили AI-соперников для тренажера возражений',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_opponents_difficulty', 'opponents', ['difficulty'], unique=False)
    op.alter_column('opponents', 'stats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"avg_score": 0, "total_attempts": 0, "users_completed": 0}\'::jsonb'))
    op.alter_column('opponents', 'base_prompt',
               existing_type=sa.TEXT(),
               comment='Базовый промпт для AI с описанием роли',
               existing_nullable=False)
    op.alter_column('opponents', 'response_patterns',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Паттерны реакций соперника',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('opponents', 'triggers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Что вызывает агрессию/интерес у соперника',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('opponents', 'core_objections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Массив основных возражений соперника',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_table_comment(
        'knowledge_base',
        'База знаний о продукте для AI-тренажера',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_knowledge_base_source_doc'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_priority'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.create_index('idx_knowledge_base_question_search', 'knowledge_base', [sa.text("to_tsvector('russian'::regconfig, question::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_knowledge_base_priority', 'knowledge_base', [sa.text('priority DESC')], unique=False)
    op.create_index('idx_knowledge_base_keywords', 'knowledge_base', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_knowledge_base_category', 'knowledge_base', ['category'], unique=False)
    op.create_index('idx_knowledge_base_answer_search', 'knowledge_base', [sa.text("to_tsvector('russian'::regconfig, answer)")], unique=False, postgresql_using='gin')
    op.alter_column('knowledge_base', 'priority',
               existing_type=sa.INTEGER(),
               comment='Приоритет информации (чем выше, тем важнее)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_base', 'keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ключевые слова для быстрого поиска релевантной информации',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('knowledge_base', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Категория: цены, документы, партнеры, компенсация, легальность и т.д.',
               existing_nullable=False)
    op.drop_index(op.f('ix_content_types_code'), table_name='content_types')
    op.create_unique_constraint('content_types_code_key', 'content_types', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'content_posts', type_='foreignkey')
    op.drop_constraint(None, 'content_posts', type_='foreignkey')
    op.create_foreign_key('content_posts_idea_id_fkey', 'content_posts', 'content_ideas', ['idea_id'], ['id'])
    op.create_foreign_key('content_posts_user_id_fkey', 'content_posts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_content_posts_user_id'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_status'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_platform'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_idea_id'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_created_at'), table_name='content_posts')
    op.create_index('idx_content_posts_user_id', 'content_posts', ['user_id'], unique=False)
    op.create_index('idx_content_posts_idea_id', 'content_posts', ['idea_id'], unique=False)
    op.drop_constraint(None, 'content_personal_profiles', type_='foreignkey')
    op.create_foreign_key('content_personal_profiles_user_id_fkey', 'content_personal_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_content_personal_profiles_user_id'), table_name='content_personal_profiles')
    op.create_unique_constraint('content_personal_profiles_user_id_key', 'content_personal_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('content_personal_profiles', 'profile_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'content_ideas', type_='foreignkey')
    op.drop_constraint(None, 'content_ideas', type_='foreignkey')
    op.create_foreign_key('content_ideas_user_id_fkey', 'content_ideas', 'users', ['user_id'], ['id'])
    op.create_foreign_key('content_ideas_content_type_id_fkey', 'content_ideas', 'content_types', ['content_type_id'], ['id'])
    op.drop_index(op.f('ix_content_ideas_user_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_platform'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_is_saved'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_is_archived'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_created_at'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_content_type_id'), table_name='content_ideas')
    op.create_index('idx_content_ideas_user_saved', 'content_ideas', ['user_id', 'is_saved', sa.text('created_at DESC')], unique=False, postgresql_where='(is_archived = false)')
    op.create_index('idx_content_ideas_user_id', 'content_ideas', ['user_id'], unique=False)
    op.create_index('idx_content_ideas_content_type_id', 'content_ideas', ['content_type_id'], unique=False)
    op.add_column('ai_training_sessions', sa.Column('feedback_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('ai_training_sessions', sa.Column('current_attempt', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'ai_training_sessions',
        'Сессии тренировок с AI-соперниками',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_ai_training_sessions_user_score'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_user_id'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_started_at'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_opponent_id'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_is_active'), table_name='ai_training_sessions')
    op.create_index('idx_ai_training_sessions_user_id', 'ai_training_sessions', ['user_id'], unique=False)
    op.create_index('idx_ai_training_sessions_started_at', 'ai_training_sessions', [sa.text('started_at DESC')], unique=False)
    op.create_index('idx_ai_training_sessions_opponent_id', 'ai_training_sessions', ['opponent_id'], unique=False)
    op.create_index('idx_ai_training_sessions_is_active', 'ai_training_sessions', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('ai_training_sessions', 'scores',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Детальные оценки: {product_knowledge, objection_handling, emotional_intelligence, confidence, result}',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_training_sessions', 'weaknesses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Слабые стороны пользователя',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_training_sessions', 'strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Сильные стороны пользователя',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_training_sessions', 'recommendations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Массив рекомендаций для пользователя',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_training_sessions', 'user_score',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               comment='Итоговая оценка от 1 до 10',
               existing_nullable=True)
    op.drop_constraint(None, 'ai_generations', type_='foreignkey')
    op.create_foreign_key('ai_generations_user_id_fkey', 'ai_generations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_generations_user_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_telegram_message_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_mode'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_expires_at'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_created_at'), table_name='ai_generations')
    op.create_index('idx_ai_generations_user_id', 'ai_generations', ['user_id'], unique=False)
    op.create_index('idx_ai_generations_telegram_message_id', 'ai_generations', ['telegram_message_id'], unique=False)
    op.create_index('idx_ai_generations_expires_at', 'ai_generations', ['expires_at'], unique=False)
    op.alter_column('ai_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_generations', 'mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ai_generations', 'telegram_message_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'todo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])", name='tasks_priority_check'),
    sa.CheckConstraint("status::text = ANY (ARRAY['todo'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name='tasks_status_check'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='tasks_progress_check'),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], name='fk_category', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('idx_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index('idx_tasks_tags', 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_order_index', 'tasks', ['order_index'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_category_id', 'tasks', ['category_id'], unique=False)
    op.create_table('task_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='task_categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_task_categories_user_id', 'task_categories', ['user_id'], unique=False)
    op.create_table('travel_hidden_gems',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('place_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('5.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("place_type = ANY (ARRAY['local_cafe'::text, 'craft'::text, 'nature'::text, 'culture'::text, 'activity'::text, 'other'::text])", name='travel_hidden_gems_place_type_check'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name='travel_hidden_gems_submitted_by_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='travel_hidden_gems_pkey')
    )
    op.create_index('idx_travel_hidden_gems_submitted_by', 'travel_hidden_gems', ['submitted_by_user_id'], unique=False)
    op.create_index('idx_travel_hidden_gems_location', 'travel_hidden_gems', ['city', 'country'], unique=False)
    op.create_table('document_metadata',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_metadata_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('travel_tours',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hotel_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location_city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location_country', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), sa.Computed('((end_date - start_date) + 1)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('price_travel_advantage', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_booking', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('savings_amount', sa.NUMERIC(precision=10, scale=2), sa.Computed('(price_booking - price_travel_advantage)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('full_itinerary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('screenshot_ta_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('screenshot_booking_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['draft'::text, 'finalized'::text, 'archived'::text])", name='travel_tours_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='travel_tours_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='travel_tours_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_travel_tours_user_id', 'travel_tours', ['user_id'], unique=False)
    op.create_index('idx_travel_tours_location', 'travel_tours', ['location_city', 'location_country'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('all_day', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reminder_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('recurrence_rule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], name='fk_category', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='fk_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='calendar_events_pkey')
    )
    op.create_index('idx_calendar_events_user_id', 'calendar_events', ['user_id'], unique=False)
    op.create_index('idx_calendar_events_event_date', 'calendar_events', ['event_date'], unique=False)
    op.create_index('idx_calendar_events_category_id', 'calendar_events', ['category_id'], unique=False)
    op.create_table('document_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['document_metadata.id'], name='document_rows_dataset_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_rows_pkey')
    )
    op.create_index('idx_document_rows_dataset_id', 'document_rows', ['dataset_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    op.create_table('travel_events_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('ticketmaster_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('api_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() + '24:00:00'::interval)"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='travel_events_cache_pkey'),
    sa.UniqueConstraint('ticketmaster_id', name='travel_events_cache_ticketmaster_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_travel_events_city_date', 'travel_events_cache', ['city', 'event_date'], unique=False)
    op.create_table('n8n_chat_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='n8n_chat_histories_pkey')
    )
    op.create_table('travel_api_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tour_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('api_service', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cost_estimated', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['travel_tours.id'], name='travel_api_logs_tour_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='travel_api_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='travel_api_logs_pkey')
    )
    op.create_index('idx_travel_api_logs_user_id', 'travel_api_logs', ['user_id'], unique=False)
    op.create_index('idx_travel_api_logs_user_created', 'travel_api_logs', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_travel_api_logs_tour_id', 'travel_api_logs', ['tour_id'], unique=False)
    op.create_index('idx_travel_api_logs_created_at', 'travel_api_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###

    # Manually added functions
    op.execute("DROP FUNCTION IF EXISTS public.update_updated_at_column();")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")
