"""Create initial tables

Revision ID: 6c3bec1ee993
Revises: 
Create Date: 2025-12-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3bec1ee993'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('telegram_bot_referral_link', sa.String(), nullable=True),
    sa.Column('referred_by_user_id', sa.UUID(), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('consultant_name', sa.String(), nullable=True),
    sa.Column('consultant_photo_url', sa.String(), nullable=True),
    sa.Column('consultant_description', sa.Text(), nullable=True),
    sa.Column('consultant_instagram', sa.String(), nullable=True),
    sa.Column('consultant_whatsapp', sa.Text(), nullable=True),
    sa.Column('consultant_telegram', sa.String(), nullable=True),
    sa.Column('consultant_email', sa.String(), nullable=True),
    sa.Column('consultant_phone', sa.String(), nullable=True),
    sa.Column('consultant_youtube', sa.String(), nullable=True),
    sa.Column('voice_passive_income_id', sa.String(), nullable=True),
    sa.Column('voice_free_travel_id', sa.String(), nullable=True),
    sa.Column('voice_freedom_id', sa.String(), nullable=True),
    sa.Column('voice_final_cta_id', sa.String(), nullable=True),
    sa.Column('welcome_video_id', sa.String(), nullable=True),
    sa.Column('current_bot_menu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by_user_id'), 'users', ['referred_by_user_id'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('opponents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('personality_type', sa.String(length=50), nullable=True),
    sa.Column('communication_style', sa.Text(), nullable=True),
    sa.Column('core_objections', sa.JSON(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('response_patterns', sa.JSON(), nullable=True),
    sa.Column('base_prompt', sa.Text(), nullable=False),
    sa.Column('voice_style', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cta_strategy', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_types_code'), 'content_types', ['code'], unique=True)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('source_doc', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_category'), 'knowledge_base', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_priority'), 'knowledge_base', ['priority'], unique=False)
    op.create_index(op.f('ix_knowledge_base_source_doc'), 'knowledge_base', ['source_doc'], unique=False)
    op.create_table('ai_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_message_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_created_at'), 'ai_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_generations_expires_at'), 'ai_generations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ai_generations_mode'), 'ai_generations', ['mode'], unique=False)
    op.create_index(op.f('ix_ai_generations_telegram_message_id'), 'ai_generations', ['telegram_message_id'], unique=False)
    op.create_index(op.f('ix_ai_generations_user_id'), 'ai_generations', ['user_id'], unique=False)
    op.create_table('radar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_events_action_type'), 'radar_events', ['action_type'], unique=False)
    op.create_index(op.f('ix_radar_events_created_at'), 'radar_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_radar_events_lead_id'), 'radar_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_radar_events_partner_id'), 'radar_events', ['partner_id'], unique=False)
    op.create_table('content_personal_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_content_personal_profiles_user_id'), 'content_personal_profiles', ['user_id'], unique=True)
    op.create_table('profile_voice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_voice_sessions_is_active'), 'profile_voice_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_profile_voice_sessions_user_id'), 'profile_voice_sessions', ['user_id'], unique=False)
    op.create_table('ai_training_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opponent_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('user_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_training_sessions_is_active'), 'ai_training_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_opponent_id'), 'ai_training_sessions', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_started_at'), 'ai_training_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_user_id'), 'ai_training_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_training_sessions_user_score'), 'ai_training_sessions', ['user_score'], unique=False)
    op.create_table('content_ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_ideas_content_type_id'), 'content_ideas', ['content_type_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_created_at'), 'content_ideas', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_ideas_is_archived'), 'content_ideas', ['is_archived'], unique=False)
    op.create_index(op.f('ix_content_ideas_is_saved'), 'content_ideas', ['is_saved'], unique=False)
    op.create_index(op.f('ix_content_ideas_platform'), 'content_ideas', ['platform'], unique=False)
    op.create_index(op.f('ix_content_ideas_user_id'), 'content_ideas', ['user_id'], unique=False)
    op.create_table('profile_voice_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['profile_voice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_voice_chunks_sequence_number'), 'profile_voice_chunks', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_profile_voice_chunks_session_id'), 'profile_voice_chunks', ['session_id'], unique=False)
    op.create_table('training_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_voice', sa.Boolean(), nullable=True),
    sa.Column('voice_file_id', sa.Text(), nullable=True),
    sa.Column('emotional_tone', sa.String(length=50), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_conversations_session_id'), 'training_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_conversations_timestamp'), 'training_conversations', ['timestamp'], unique=False)
    op.create_table('content_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_posts_created_at'), 'content_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_posts_idea_id'), 'content_posts', ['idea_id'], unique=False)
    op.create_index(op.f('ix_content_posts_platform'), 'content_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_content_posts_status'), 'content_posts', ['status'], unique=False)
    op.create_index(op.f('ix_content_posts_user_id'), 'content_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_posts_user_id'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_status'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_platform'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_idea_id'), table_name='content_posts')
    op.drop_index(op.f('ix_content_posts_created_at'), table_name='content_posts')
    op.drop_table('content_posts')
    op.drop_index(op.f('ix_training_conversations_timestamp'), table_name='training_conversations')
    op.drop_index(op.f('ix_training_conversations_session_id'), table_name='training_conversations')
    op.drop_table('training_conversations')
    op.drop_index(op.f('ix_profile_voice_chunks_session_id'), table_name='profile_voice_chunks')
    op.drop_index(op.f('ix_profile_voice_chunks_sequence_number'), table_name='profile_voice_chunks')
    op.drop_table('profile_voice_chunks')
    op.drop_index(op.f('ix_content_ideas_user_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_platform'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_is_saved'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_is_archived'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_created_at'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_content_type_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_ai_training_sessions_user_score'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_user_id'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_started_at'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_opponent_id'), table_name='ai_training_sessions')
    op.drop_index(op.f('ix_ai_training_sessions_is_active'), table_name='ai_training_sessions')
    op.drop_table('ai_training_sessions')
    op.drop_index(op.f('ix_profile_voice_sessions_user_id'), table_name='profile_voice_sessions')
    op.drop_index(op.f('ix_profile_voice_sessions_is_active'), table_name='profile_voice_sessions')
    op.drop_table('profile_voice_sessions')
    op.drop_index(op.f('ix_content_personal_profiles_user_id'), table_name='content_personal_profiles')
    op.drop_table('content_personal_profiles')
    op.drop_index(op.f('ix_radar_events_partner_id'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_lead_id'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_created_at'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_action_type'), table_name='radar_events')
    op.drop_table('radar_events')
    op.drop_index(op.f('ix_ai_generations_user_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_telegram_message_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_mode'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_expires_at'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_created_at'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_knowledge_base_source_doc'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_priority'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_category'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_content_types_code'), table_name='content_types')
    op.drop_table('content_types')
    op.drop_table('opponents')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
